version: '3.8'

services:
  app:
    build: .
    image: ticket_splitter:latest
    container_name: ticket_splitter_prod
    restart: unless-stopped
    environment:
      - MIX_ENV=prod
      - PHX_SERVER=true
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:napi_p6urfdl84sudd4f57qeod8ganilmp9qne4r574y39bme2bn6iuva242awhsq9chh@ep-red-mountain-49266409.us-east-1.aws.neon.tech/db?sslmode=require
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_HOST=${PHX_HOST:-localhost}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL:-openai/gpt-4o}
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - ticket_network

  db:
    image: postgres:15-alpine
    container_name: ticket_splitter_db_prod
    restart: unless-stopped
    environment:
      - POSTGRES_DB=ticket_splitter_prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticket_network

volumes:
  postgres_data:

networks:
  ticket_network:
    driver: bridge